services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_container
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: sync-engine-user
      DB_PASSWORD: password
      DB_NAME: mydb
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    container_name: db_container
    environment:
      POSTGRES_USER: sync-engine-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
